# Generated by Django 3.0.4 on 2020-04-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(blank=True, null=True, upload_to='evebt_pictures', verbose_name='Foto de evento'),
        ),
    ]
