# Generated by Django 3.1 on 2020-08-11 06:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='Nombre')),
                ('replacement_price', models.IntegerField(default=0, verbose_name='Precio de reposición')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='product_stamp', verbose_name='Estampa de producto')),
                ('inscription', models.TextField(blank=True, null=True, verbose_name='Inscripción')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_photo', verbose_name='Foto de producto')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.article')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('date_order', models.DateField(default=datetime.date.today, verbose_name='Fecha de Pedido')),
                ('date_delivery', models.DateField(default=datetime.date(2020, 8, 16), verbose_name='Fecha de Entrega')),
                ('deposit', models.IntegerField(default=0, verbose_name='Adelanto')),
                ('ticket', models.IntegerField(default=0, verbose_name='Factura')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
