# Generated by Django 3.1 on 2020-08-12 00:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(default=datetime.date(2020, 8, 17), verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.article', verbose_name='Artículo'),
        ),
    ]
