# Generated by Django 3.1 on 2020-08-15 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200812_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(default=datetime.date(2020, 8, 20), verbose_name='Fecha de Entrega'),
        ),
    ]
