# Generated by Django 3.1 on 2020-09-18 02:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200815_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='Categoría')),
                ('icon', models.ImageField(upload_to='icon_category', verbose_name='Ícono')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inscription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stamp',
        ),
        migrations.AddField(
            model_name='article',
            name='code',
            field=models.IntegerField(default=0, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(default=datetime.date(2020, 9, 23), verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
