# Generated by Django 3.1 on 2020-09-27 21:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_auto_20200926_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(default=datetime.date(2020, 10, 2), verbose_name='Fecha de Entrega'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(verbose_name='fch Nacimiento')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Cód Postal')),
                ('telephone', models.IntegerField(max_length=15, verbose_name='Teléfono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
