# Generated by Django 3.1 on 2020-10-12 21:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_auto_20200927_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=8, unique=True, verbose_name='Cód Postal')),
                ('amount', models.IntegerField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Costo de envío',
                'verbose_name_plural': 'Costos de envíos',
            },
        ),
        migrations.AlterField(
            model_name='favorite',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_r', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_r', to='product.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(default=datetime.date(2020, 10, 17), verbose_name='Fecha de Entrega'),
        ),
    ]
