# Generated by Django 3.1 on 2020-10-21 01:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201012_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(default='', verbose_name='Descripción')),
                ('replacement_price', models.IntegerField(default=0, verbose_name='Precio de reposición')),
                ('stock', models.IntegerField(default=0, verbose_name='Disponibles')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='article',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(default=datetime.date(2020, 10, 26), verbose_name='Fecha de Entrega'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='product',
            name='supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.supply', verbose_name='Artículo'),
        ),
    ]
