# Generated by Django 3.1 on 2020-10-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20201021_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('OR', 'Order'), ('AC', 'Accept'), ('PR', 'In_Process'), ('DE', 'Delivered')], default='OR', max_length=2),
        ),
    ]
