# Generated by Django 3.1 on 2020-10-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('OR', 'Pedido'), ('AC', 'Aceptado'), ('PR', 'En proceso'), ('FN', 'Terminado'), ('DE', 'Entregado'), ('RJ', 'Rechazado'), ('CC', 'Cancelado')], default='OR', max_length=2),
        ),
    ]
