# Generated by Django 3.1 on 2020-10-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20201021_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_status',
        ),
        migrations.AddField(
            model_name='order',
            name='product_status',
            field=models.CharField(choices=[('OR', 'Pedido'), ('AC', 'Aceptado'), ('PR', 'En proceso'), ('FN', 'Terminado'), ('DE', 'Entregado'), ('RJ', 'Rechazado'), ('CC', 'Cancelado')], default='OR', max_length=2),
        ),
    ]
