# Generated by Django 3.1 on 2020-10-23 04:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20201021_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('description', models.TextField(default='', verbose_name='Descripción')),
                ('replacement_price', models.IntegerField(default=0, verbose_name='Precio de reposición')),
                ('stock', models.IntegerField(default=0, verbose_name='Disponibles')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.RemoveField(
            model_name='supply',
            name='code',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='replacement_price',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='stock',
        ),
        migrations.AddField(
            model_name='supply',
            name='cant_per_prod',
            field=models.IntegerField(default=1, verbose_name='Cantidad por por producto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(default=datetime.date(2020, 10, 28), verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='supply',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.component', verbose_name='Componente'),
        ),
    ]
