# Generated by Django 3.1 on 2020-11-28 04:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20201023_0409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Stock disponible', 'verbose_name_plural': 'Stock disponible'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateField(default=datetime.date(2020, 12, 3), verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ticket',
            field=models.IntegerField(default=0, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.supply', verbose_name='Insumo'),
        ),
    ]
