# Generated by Django 3.1 on 2020-08-10 04:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0002_auto_20200809_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='event_picture',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='title',
        ),
        migrations.AddField(
            model_name='pedido',
            name='adelanto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='factura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(default=datetime.date(2020, 8, 15)),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('insumo', models.TextField(blank=True, null=True, verbose_name='descripcion')),
                ('estampa', models.ImageField(blank=True, null=True, upload_to='producto_estampa', verbose_name='Estampa de producto')),
                ('inscripcion', models.TextField(blank=True, null=True, verbose_name='inscripcion')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='producto_estampa', verbose_name='Estampa de producto')),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.pedido')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
