# Generated by Django 3.1 on 2020-08-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20200810_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='producto_foto', verbose_name='Foto de producto'),
        ),
    ]
